### ISSUE TITLE
Cannot find module './'

### ISSUE THREAD

**Issue by BallisticOK** [IAmParadox27/jellyfin-plugin-custom-tabs#24]
i dont really know what to put 

im running the latest jellyfin using docker the latest copy of the plugin and used the example from the readme to setup my button to the page i want it to display witch is my jellyserr or what ever its called but it dont load the button is there but it is just a blank page and the only error i get is

main.jellyfin.bundle…d6486af79af0b5be2:2 
 Uncaught (in promise) Error: Cannot find module './'
    at main.jellyfin.bundle…79af0b5be2:2:491586

**Comment by UIMLink** [comment]
Also getting this issue haven't really found a way around it. As far as i can tell in chrome nothing shows up and in Firefox it says its trying to access it within the existing domain even though it's a subdomain. Ex:

https://jellyfin.xyz/web/sub.domain.xyz/
sub.domain.xyz is what i put in the provided html for the plugin

Interestingly enough it does work when I don't use the domain and go straight to jellyfin over VPN but I don't have any rules for my domain through cloud flare nor the reverse proxy.

**Comment by ultrawazer** [comment]
Any idea when this will be resolved? 
Or what is causing this issue? 

I am getting this issue, and at random they magically loaded once, but never again.

**Comment by IAmParadox27** [comment]
> Hi,
> 
> I finally got Custom Tabs to work, but only with these specific versions:
> 
> * Jellyfin (official Docker image) v10.10.7
> * File Transformation v2.2.1.0
> * Custom Tabs v1.5.0
> 
> Important note: If I install the latest File Transformation plugin, the well-known "Cannot find module './'" error appears and Custom Tabs fails to load. With the version 2.2.1.0 of File Transformation everything works as expected.
> 
> Hope this helps anyone facing the same issue.

This is useful to figure out what's happening - I'll take a look when I get some free time and see if I can figure out why the latest FT version doesn't work, but 2.2.1 does

**Comment by McCio** [comment]
FYI @IAmParadox27 , it also happens with this combination: 
- Custom tabs: 0.2.0.0
- File Transformation: 2.4.0.0
- Jellyfin: 10.11.0

**Comment by developerwill** [comment]
FYI @IAmParadox27  this also happens with these:

- Custom tabs: 0.2.2.0
- File Transformation: 2.4.2.0
- Jellyfin: 10.11.2

**Comment by Manbearpig92** [comment]
Yes I had it loaded the other day but my server crashed and I had to reinstall the official container on unraid and I can't find it in the catalog either

**Comment by SpeeDFireCZE** [comment]
To me it was docker updates, or some system update. After I updated host this problem disappear for me.

**Comment by gab-palmeri** [comment]
Still facing this problem, right after updating from 10.10.7 to 10.11.6

**Comment by IAmParadox27** [comment]
Please uninstall all my plugins and install the latest versions of each - even if you had the latest previously installed. This could be related to the upgrade not detecting different binaries for each ABI

**Comment by TheFoxStudio** [comment]
Freshly installed plugin after upgrade. same error.
Jellyfin 10.11.6
File Transformation: 2.5.3.0
Custom Tabs:  0.2.6.0

**Comment by Chat-mots** [comment]
same config as @TheFoxStudio, and i have the "cannot find module './' error. It was a fresh install with Docker.

**Comment by Chat-mots** [comment]
It seems it is a caching error, using a private browser window fixes the issue. For those having this issue, try emptying the cache.

Not only ctrl+f5, but "clear cookies and site data".

**Comment by TsunamicFlame** [comment]
@IAmParadox27 I'm also having this issue, I'm on Jellyfin 10.11.9. I was able to get content to show on the page, but only after using Chat-mots's "clear cookies and site data" suggestion. However, even with content showing on the page, the console log still shows the same error.

It would also appear that in order to see the updates for any page, the cache must be cleared manually again. At least in my specific scenario.

Hope this info helps, I really like this plugin and hope to use it in my system.
